### ISSUE TITLE
Download Quarantänebescheinigung funktioniert nicht (Safari 14)

### ISSUE THREAD

**Issue by t0bska** [ImisDevelopers/SORMAS-Project#29]
### Bug Description
Es wird kein Dokument heruntergeladen.
Netzwerkanalyse ergibt: 
<img width="761" alt="image" src="https://user-images.githubusercontent.com/43952751/95767324-df9a2580-0cb4-11eb-9ef4-ec848cdbcbe5.png">

### Steps to Reproduce
1.Use Safari 14
2.Quarantäneanordnung erstellen: auf erstellen klicken

### System Details
* Device: MacOS
* SORMAS version: feature-2696-document-generation-quarantine
* Android version/Browser: Safari 14
* User Role: SurvSup

**Comment by syntakker** [comment]
@t0bska Ist dieser Bug noch aktuell? Kann ihn leider nicht reproduzieren, kein Safari.

**Comment by t0bska** [comment]
is fixed
