### ISSUE TITLE
Clarify list of placeholders

### ISSUE THREAD

**Issue by syntakker** [ImisDevelopers/SORMAS-Project#3]
Clarify list of placeholders in quarantine related document available from SORMAS.

Values for placeholders must be available in the context of quarantine and must have a mapping to (values from) entities in SORMAS.

**Comment by JonasCir** [comment]
Let's get this started! :)

**Comment by JonasCir** [comment]
I was able to map the most frequent placeholders present in our sample set to SORMAS data entities. Mapping is straight forward, I will share it this weekend.
