### ISSUE TITLE
Backend: Template Service

### ISSUE THREAD

**Issue by syntakker** [ImisDevelopers/SORMAS-Project#5]
A service providing:

- [ ] ~~persisting a template on PostgreSQL along with meta data (here: the workflow for which the template is relevant)~~
- [ ] ~~reading a template from PostgreSQL~~
- [x] reading a list of templates available for a workflow
- [x] deleting a template

Templates are docx files. "List of templates" means list of identifiers as used for reading a template from DB. Workflow identifiers have to be agreed upon.

**Comment by JonasCir** [comment]
@s8jorenc works on this! :+1:

**Comment by syntakker** [comment]
Persistence in PostgreSQL has been omitted from the implementation for now.

**Comment by JonasCir** [comment]
See https://github.com/hzi-braunschweig/SORMAS-Project/issues/2328
